# Change these first
owner: m1xzg # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository
runner: "[self-hosted]"

sites:
  - name: Zoraxy
    url: http://bigbastard.letmeshoot.it:8000
    icon: https://github.com/tobychui/zoraxy/blob/main/src/web/favicon.png
  - name: Dashboard
    url: https://dash.rpmdp.com/freeboard/
    icon: https://dash.rpmdp.com/freeboard/dashicon.png
    #expectedStatusCodes:
    #  - 200
    #  - 201
    #  - 403
  - name: FB
    url: https://fb.letmeshoot.it/login
    #expectedStatusCodes:
    #  - 200
    #  - 201
    #  - 403
  - name: Flight Tracker (FA)
    url: https://fa.letmeshoot.it
    #expectedStatusCodes:
    #  - 200
    #  - 201
    #  - 403
  - name: Flight Tracker (FT)
    url: https://ft.letmeshoot.it
    #expectedStatusCodes:
    #  - 200
    #  - 201
    #  - 403
  - name: Wildys Lore
    url: https://lore.wildwanderer-vr.com
    #expectedStatusCodes:
    #  - 200
    #  - 201
    #  - 403
  - name: Blog
    url: https://www.uk-experience.com
  - name: Reggie Walks
    url: https://www.reggiewalkswitney.co.uk
  - name: pi4-1 http
    url: http://pi4-1.zt.rpmdp.com
    icon: https://raw.githubusercontent.com/iiiypuk/rpi-icon/refs/heads/master/32.png
  - name: pi4-2 http
    url: http://pi4-2.zt.rpmdp.com:8080
    icon: https://raw.githubusercontent.com/iiiypuk/rpi-icon/refs/heads/master/32.png
  - name: NAS
    url: http://172.16.29.2
    icon: https://github.com/M1XZG/uptime/blob/1159284a2dacde9ad753831599fab5ebe7caa7a8/assets/truenas-logo.png
  - name: Fritzbox
    url: http://172.16.29.251
    icon: https://github.com/M1XZG/uptime/blob/aabd86d900f29e35c0ab5c7dd9797b8a20614469/assets/Fritzbox.png
    

#  - name: Home
#    url: https://home.rpmdp.com
#  - name: Minecraft Map
#    url: http://bigbastard.letmeshoot.it:8123


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.rpmdp.com # Custom domain CNAME
  #baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: My Servers
  introTitle: "Uptime Monitoring!"
  introMessage: ""
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: Robs Servers
      href: https://github.com/$OWNER/$REPO
#
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
