# Change these first
owner: m1xzg # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository
runner: "[self-hosted]"

sites:
  - name: Zoraxy
    url: http://bigbastard.letmeshoot.it:8000
    icon: https://github.com/tobychui/zoraxy/blob/main/src/web/favicon.png
  - name: Dashboard
    url: http://dash.rpmdp.com/freeboard/
    icon: http://dash.rpmdp.com/freeboard/dashicon.png
  - name: FileBrowser
    url: https://fb.letmeshoot.it/login
  - name: Flight Tracker (FA)
    url: https://fa.letmeshoot.it
  - name: Flight Tracker (FT)
    url: https://ft.letmeshoot.it
  - name: Wildys Lore
    url: https://lore.wildwanderer-vr.com
    #expectedStatusCodes:
    #  - 200
    #  - 201
    #  - 403
  - name: Blog
    url: https://www.uk-experience.com
  - name: Reggie Walks
    url: https://www.reggiewalkswitney.co.uk
  - name: pi4-1 http [VPN]
    url: $PI41ADDR
    icon: https://github.com/M1XZG/uptime/blob/a5f5569c652410f39f06ead23e0166ef84abb697/assets/RaspPi-32px.png
  - name: pi4-2 http [VPN]
    url: $PI42ADDR
    icon: https://github.com/M1XZG/uptime/blob/a5f5569c652410f39f06ead23e0166ef84abb697/assets/RaspPi-32px.png
  - name: StreamingPC [VPN]
    url: $STREAMINGADDR
    icon: https://github.com/M1XZG/uptime/blob/e7395f2d4ab9e8fc2ae49ab9be25c7d7335d5224/assets/Windows-11-Icon.png
    expectedStatusCodes:
      - 401
  - name: NAS [VPN]
    url: $NASADDR
    icon: https://github.com/M1XZG/uptime/blob/7e0b96e646434818c69ecd093ff1db4c5a2c4bf3/assets/truenas-logo.png
  - name: Fritzbox [VPN]
    url: $FRITZADDR
    icon: https://github.com/M1XZG/uptime/blob/7e0b96e646434818c69ecd093ff1db4c5a2c4bf3/assets/Fritzbox.png
  - name: Tinkerbell [VPN]
    url: $TINKERBELLADDR
    check: "tcp-ping"
    port: 53
    icon: https://github.com/M1XZG/uptime/blob/7e0b96e646434818c69ecd093ff1db4c5a2c4bf3/assets/tinkerboard.png
    
    

#  - name: Home
#    url: https://home.rpmdp.com
#  - name: Minecraft Map
#    url: http://bigbastard.letmeshoot.it:8123


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.rpmdp.com # Custom domain CNAME
  #baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: My Servers
  introTitle: "Uptime Monitoring!"
  introMessage: ""
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: Robs Servers
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/3 * * * *"
#
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
