# Change these first
owner: m1xzg # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository
runner: "[self-hosted]"

sites:
  - name: Zoraxy
    url: http://bigbastard.letmeshoot.it:8000
  - name: Dashboard
    url: https://dash.rpmdp.com/freeboard/
  - name: FB
    url: https://fb.letmeshoot.it/login
  - name: Flight Tracker (FA)
    url: https://fa.letmeshoot.it
  - name: Flight Tracker (FT)
    url: https://ft.letmeshoot.it
  - name: Blog
    url: https://www.uk-experience.com
  - name: Reggie Walks
    url: https://www.reggiewalkswitney.co.uk
  - name: pi4-1 http [VPN]
    url: $PI41ADDR 
  - name: pi4-2 http [VPN]
    url: $PI42ADDR
  - name: Edge Router [via VPN]
    url: $EDGEROUTERADDR
  - name: Helios (Streaming PC)
    url: $HELIOSADDR
    check: "tcp-ping"
    port: 4445

  - name: Google DNS 1
    check: "tcp-ping"
    url: 8.8.4.4
    port: 53
  - name: Google DNS 2
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Robs Servers
  introTitle: "Uptime Monitoring!"
  introMessage: ""
  theme: mytheme
  navbar:
    - title: Status
      href: /
    - title: Robs Servers
      href: https://github.com/$OWNER/$REPO
#
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration


